### ISSUE TITLE
Separating loading of the NVDLA loadable and jpg image

### ISSUE THREAD

**Issue by ned-varnica** [nvdla/sw#53]
Hi @prasshantg 

I am re-opening issue #52 , as it seems to be different from #38 

What we are trying to do is process live-video: So outputs are needed frame by frame (with no delay or minimal delay), The way we try to run it is as follows:  

We break a video into N frames and run it as:  
nvdla_runtime –l resnet50.nvdla –i frame_1.jpg
nvdla_runtime  –i frame_2.jpg
…
nvdla_runtime  –i frame_N.jpg

In other words, we are looking for a way to load the nvdla loadable once and then call the same function with different frames, without having to load that file again (if the loadable is in the memory and this memory is not changed, this should work). However, we do not get meaningful result. 

The way we understand #38 is that several jpg files can run in the internal loop.  The problem is that the latency of showing the live video (from when frame n is available, to the time it is finished processing) would be the time that it takes to load the loadable (+ a little bit more for processing).  The bottleneck is in loading the loadable (very long) and makes the processed live video appear delayed by several seconds.  

Please correct me if you feel that we can process live video in any other way, and get the outputs frame by frame with the latency being similar to the processing delay. 

thanks very much!

**Comment by prasshantg** [comment]
@ned-varnica current application does not support processing video or multiple images without reloading loadable. But we already provide interfaces which separates out loading loadable and running inference on image.

Test application executes below steps
1. readLoadable
2. loadLoadable
3. runTest
4. unloadLoadable

What you need to do is execute steps 1 and 2 just once when launching application and execute runTest function for each image or frame in video.

You will have to do changes for this in test application as we are not currently supporting it. We will support it but not in near future. You can contribute back changes for this feature if you can get it done.

**Comment by ned-varnica** [comment]
@prasshantg  Thanks very much for a detailed answer.   

We will try to get it done.

**Comment by jayaramv14** [comment]
Hi @prasshantg @ned-varnica ,

I have been working on running multiple frames using NVDLA virtual platform. Using the latest NVDLA/sw. 

Mechanism: 
I have created an extra application which will send the image file name through message queue to nvdla_runtime application running in virtual platform. The nvdla_runtime applicaiton, 
a. read loadable,
b. load loadable,
c. wait for the message queue for the image file name.
d. runTest .
**the steps c and d are in a while forever loop.**

First iteration is successful, but in the second iteration I am getting the following error,

./nvdia_runtime --loadable fast-math.nvdla --image 1.pgm
Emulator starting
Create Key
 Get message ID
 Read Message 

# 
# ./nvdla_runtime1 4.pgm 
 File Path is : 4.pgm 
[   83.202022] nvdla_runtime[1275]: unhandled level 2 translation fault (11) at 0x00000000, esr 0x92000046, in libc-2.23.so[ffff90a4f000+12c000]
[   83.202928] CPU: 0 PID: 1275 Comm: nvdla_runtime Tainted: G           O    4.13.3 #1
[   83.204562] Hardware name: linux,dummy-virt (DT)
[   83.204890] task: ffff80003da81c00 task.stack: ffff80003c534000
[   83.205361] PC is at 0xffff90ac73f8
[   83.205540] LR is at 0xffff90da8f1c
[   83.205732] pc : [<0000ffff90ac73f8>] lr : [<0000ffff90da8f1c>] pstate: 80000000
[   83.206052] sp : 0000ffffc4bd5ac0
[   83.206283] x29: 0000ffffc4bd5ac0 x28: 0000000000000000 
[   83.206805] x27: 0000000000000000 x26: 0000000000000000 
[   83.215395] x25: 0000000000000005 x24: 0000000000000000 
[   83.215954] x23: 0000000000000000 x22: 0000000000000000 
[   83.216484] x21: 0000000000000000 x20: 0000000000000005 
[   83.217019] x19: 0000000000451bf0 x18: 0000000000000000 
[   83.217473] x17: 0000ffff90ac7380 x16: 0000ffff90e15600 
[   83.217737] x15: 0000000000000019 x14: 000000e000000001 
[   83.218034] x13: 0000000000000000 x12: 0000ffff9088f1e0 
[   83.218418] x11: 0000000000000001 x10: 0101010101010101 
[   83.218808] x9 : 0000000000000000 x8 : 0101010101010101 
Message:4.pgm[   83.226069] x7 : 7f7f7f7f7f7f7f7f x6 : 0000000000000000 
[   83.226554] x5 : 0000000000000000 x4 : 0000000000000005 
[   83.226815] x3 : 0000000067702e34 x2 : 0000000000000005 
[   83.227997] x1 : 000000000043ad5c x0 : 0000000000000000 
# Segmentation fault

In the first execution though i pass image name, i am ignoring in the program and waiting for second executable send the file name.

Could you help me to find the issue here.
